//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TapSystemEntities : DbContext
    {
        public TapSystemEntities()
            : base("name=TapSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblEnrolledAccount> tblEnrolledAccounts { get; set; }
        public virtual DbSet<tblMasterSetting> tblMasterSettings { get; set; }
        public virtual DbSet<tblRoute> tblRoutes { get; set; }
        public virtual DbSet<tblSubroute> tblSubroutes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblBus> tblBus1 { get; set; }
        public virtual DbSet<tblModule> tblModules { get; set; }
        public virtual DbSet<tblRetail> tblRetails { get; set; }
        public virtual DbSet<tblSystemLog> tblSystemLogs { get; set; }
        public virtual DbSet<tblTransaction> tblTransactions { get; set; }
        public virtual DbSet<tblUserMatrix> tblUserMatrices { get; set; }
        public virtual DbSet<tblBusAssignment> tblBusAssignments { get; set; }
    }
}
