//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusAssignment
    {
        public int ID { get; set; }
        public int iConductorID { get; set; }
        public int iDriverID { get; set; }
        public int iInspector { get; set; }
        public int iBusID { get; set; }
        public int iRouteID { get; set; }
        public System.DateTime dDateOfAssignment { get; set; }
        public int bActive { get; set; }
    
        public virtual tblBus tblBus { get; set; }
        public virtual tblRoute tblRoute { get; set; }
        public virtual tblUser conductor { get; set; }
        public virtual tblUser driver { get; set; }
        public virtual tblUser inspector { get; set; }
    }
}
