//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRetail
    {
        public int iRetailID { get; set; }
        public string tUsername { get; set; }
        public string tPassword { get; set; }
        public string tFullname { get; set; }
        public string tMobileNo { get; set; }
        public int bActive { get; set; }
    }
}
