//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemLog
    {
        public int iLogID { get; set; }
        public string tModuleCode { get; set; }
        public string tActivity { get; set; }
        public string tUsername { get; set; }
        public System.DateTime dDateCreated { get; set; }
    }
}
