//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int ID { get; set; }
        public string tLogMessage { get; set; }
        public int iAmount { get; set; }
        public int iRouteID { get; set; }
        public int iSubrouteID { get; set; }
        public string tPlateNo { get; set; }
        public Nullable<int> iSeatNo { get; set; }
        public System.DateTime dTransDate { get; set; }
    }
}
